### PR TITLE
allow use of less plugins through the config

### PR DESCRIPTION
**Pull request by wprater**
when I use the `less-plugin-autoprefix` plugin, this issue https://github.com/dbashford/mimosa-autoprefixer/issues/2 is fixed for me

### CODE REVIEW

**Comment by dbashford** [comment]
As of the changes I made earlier today I'm having no issues with less and autoprefixer.  Can you check that for me?

including modules is good regardless, but want to ensure something that ought to work just fine works just fine.

**Comment by wprater** [comment]
yeah, I'll check on both my projects.

**Comment by dbashford** [comment]
Two things:

1. Can you remove the note about this module not working with autoprefixer?

2. Can you add a little Example Config section that shows what using a plugin would look like in the config?  Something like this: https://github.com/dbashford/mimosa-sprite#example-config, nothing too crazy.

Thanks!

**Comment by wprater** [comment]
sure!  changes made!

**Comment by dbashford** [comment]
Awesome! Thanks!

**Pull request merged**
